### ISSUE TITLE
Question : Is there a way to start a Webview app in debug mode ?

### ISSUE THREAD

**Issue by serge-hulne** [naqvis/webview#8]
Question : Is there a way to start a Webview app in "debug mode" in order to see the messages logged on the client side (logged by JS in the web page currently displayed), as it is done in Electron, for instance ?

**Comment by naqvis** [comment]
You can enable the debug mode of webview window by passing the last parameter of `Webview#window` as `true`. Then you can open developer console of browser window by right-click.

other than this option, there is no other setting which can be enabled and you will have to add logging/tracing capabilities by yourself to the codebase you are developing.

**Comment by serge-hulne** [comment]
Thank you!
